variables:
  REPO_URL: 'http://packages.opentap.io'
  REPO_PLUGIN_DIR_NAME: 'Python'
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'
stages:
  - build
  - test
  - publish

# This job builds the solution and captures the resulting *.TapPlugin as a build artifact
Build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  tags: [ docker, gce ]
  script: 
          - dotnet build -c Release
          - cd bin/Release
          - ./tap package create ../../OpenTap.Python.TestModule/package.xml -o ../../TestModule.TapPackage
          - cp Python*.TapPackage ../..

  artifacts:
    expire_in: 1 week
    paths:
       - "*.TapPackage"
       - bin/Release/*
  
.TestPackageUbuntu:
  tags: [ docker, gce ]
  stage: test
  image: opentapio/opentap:9.17.4-bionic
  dependencies: [Build]
  script:
    - apt update
    - apt install libpython$PYTHON_VERSION -y
    - tap package install ./Python.*.TapPackage
    - tap package install ./TestModule.TapPackage
    - 'tap run /opt/tap/Packages/Python/TestModule/BasicPlan.TapPlan'
    - cd bin/Release
    - ./tap run test.TapPlan

TestPackageUbuntuPy39:
  extends: .TestPackageUbuntu
  variables: 
    PYTHON_VERSION: "3.9"

TestPackageUbuntuPy38:
  extends: .TestPackageUbuntu
  variables:
    PYTHON_VERSION: "3.8"
  

# This job publishes the *.TapPlugin to the package repository
# This job does not run automatically but requires manual action from the developer
ManualPublishOpenTapIo:
  tags: [ docker, gce ]
  stage: publish
  when: manual
  image: opentapio/opentap:9.17.4-bionic
  dependencies:
     - Build
  script: 
     - 'tap package install -f -v -r $REPO_URL "PackagePublish" --version 2'
     - 'tap package publish -v -p python -k $OPENTAP_REPO_SECRET_KEY -r packages.opentap.io Python*.TapPackage'

.BuildDoc:
  stage: build
  image: node:16.14.0
  cache:
    paths:
      - node_modules/
  script:
    - cd Documentation
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
pages:
  extends: .BuildDoc
  only: 
    - tags
buildDocTest:
  extends: .BuildDoc
  except: 
    - tags
